### ISSUE TITLE
Why Lvat can inject larger perturbation than vat?

### ISSUE THREAD

**Issue by Brownchen** [geosada/LVAT#1]
Hi, Lvat is a nice work which improved the vat. 

But I still feel confused about the reason that lvat can use larger perturbation in the latent space. The way to compute perturbation is the same for both vat and lvat. 

Is it an experimental conclusion? Or I have missed some theoretical analysis?

**Comment by geosada** [comment]
Hi, thanks for your question.
Basically, the magnitude of perturbation in LVAT (1.0-1.5) is smaller than that of VAT (2.5-8.0).
These are empirical results but are also able to be explained theoretically.
Space where the perturbation is added in LVAT is the latent space, N(0,I).
The latent space is very packed compared to the input image space because all of the images in the (training) dataset will be contained in the region of N(0,I).
Thus, the perturbation magnitude = 1.0 is sufficiently large in the latent space.
Actually, it is the hardest point all the time I have explained LVAT to someone, and thus if it's still unclear please ask again.

**Comment by Brownchen** [comment]
Thank you for your answer!!

**Comment by Brownchen** [comment]
Thank you for your answer!!
